default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: challenge-distribusion_development
  
test:
  <<: *default
  database: challenge-distribusion_test

production:
  <<: *default
  database: challenge-distribusion_production
  username: challenge-distribusion
  password: <%= ENV['MYSQL-TEST_DATABASE_PASSWORD'] %>
